### ISSUE TITLE
support flink1.16

### ISSUE THREAD

**Issue by 0xqq** [HamaWhiteGG/flink-sql-lineage#16]
Is there a plan to support Flink1.16

**Comment by HamaWhiteGG** [comment]
I will support in the next month

**Comment by HamaWhiteGG** [comment]
Flink1.16 is already supported, and the code is in the lineage-flink1.16.x module. At the same time, it also supports multiple Flink version parsing. You can view the test code in the lineage-client module.
Note that because other functions are still being developed, this part of the code has not been merged into the main branch, please check it in the release-4.0.0 branch.

https://github.com/HamaWhiteGG/flink-sql-lineage/tree/release-4.0.0

![D6E3E8C3-A42C-4BED-BEFC-4744BF06B6F3](https://user-images.githubusercontent.com/97529774/215635671-721fee58-26be-43b7-af9a-a728a90560c5.png)

**Comment by HamaWhiteGG** [comment]
finish
